# syntax=docker/dockerfile:1

# ─────────────────────────────────────────────────────────────────────────────
# Sable & Iron — app image.
# Kept intentionally simple (full dependencies retained) so that Prisma migrate
# + tsx seeding run reliably inside the container for local/demo use. For a
# slimmer production image, switch `output: "standalone"` in next.config and use
# a multi-stage runner — noted in the README under "Production hardening".
# ─────────────────────────────────────────────────────────────────────────────

FROM node:20-alpine
RUN apk add --no-cache libc6-compat openssl postgresql-client
WORKDIR /app

ENV NEXT_TELEMETRY_DISABLED=1

# Install dependencies (cached on lockfile changes).
COPY package.json package-lock.json* ./
COPY prisma ./prisma
RUN npm install

# App source.
COPY . .

# Build Next.js (Prisma client is generated by the build script).
RUN npm run build

# Writable uploads directory for reference images.
RUN mkdir -p /app/public/uploads

# Ensure the entrypoint is executable inside the image. COPY preserves the host
# file's permission bits, and the script may arrive without the exec bit (e.g.
# checked out on Windows/macOS), which causes "exec: permission denied" at start.
RUN chmod +x /app/docker-entrypoint.sh

EXPOSE 3000
# Invoke via `sh` as a belt-and-suspenders guard against a missing exec bit or
# CRLF line endings on the script.
ENTRYPOINT ["sh", "/app/docker-entrypoint.sh"]
CMD ["npm", "run", "start"]
